import type { Actions, GatsbyNode, Reporter } from 'gatsby';
import path from 'path';
import { resolvePostUrl } from './src/utilities/post/post-url-resolver';

const createTags = async (actions: Actions, reporter: Reporter, graphql) => {
  const { createPage } = actions;

  const result = await graphql(`
    query TagsQuery {
      allMdx(filter: { frontmatter: { type: { eq: "post" } } }) {
        edges {
          node {
            frontmatter {
              tags
            }
          }
        }
      }
    }
  `);

  if (result.errors) {
    reporter.panicOnBuild('🚨  ERROR: Loading "createTags" query');
  }

  const tags = result.data.allMdx.edges.flatMap(({ node }) => node.frontmatter.tags).filter(n => n);
  const uniqueTags: Array<string> = Array.from(new Set(tags));
  console.log(uniqueTags);

  uniqueTags.forEach((tag, index) => {
    createPage({
      // The slug generated by gatsby-plugin-mdx doesn't contain a slash at the beginning
      // You can prepend it with any prefix you want
      path: `/tags/${tag}`,
      // This component will wrap our MDX content
      component: path.resolve(`./src/templates/tag.tsx`),
      // You can use the values in this context in
      // our page layout component
      context: { tag: tag },
    });
  });

};

const createPosts = async (actions: Actions, reporter: Reporter, graphql) => {
  const { createPage } = actions;

  const result = await graphql(`
    query PostsQuery {
      allMdx(
        filter: { frontmatter: { type: { eq: "post" } } }
        sort: { fields: frontmatter___date, order: DESC }
      ) {
        edges {
          node {
            id
            slug
            frontmatter {
              title
              date
              slug
            }
          }
        }
      }
    }
  `);

  if (result.errors) {
    reporter.panicOnBuild('🚨  ERROR: Loading "createPosts" query');
  }

  const posts = result.data.allMdx.edges;

  posts.forEach(({ node }, index) => {
    createPage({
      // The slug generated by gatsby-plugin-mdx doesn't contain a slash at the beginning
      // You can prepend it with any prefix you want
      path: resolvePostUrl('/posts', node.frontmatter),
      // This component will wrap our MDX content
      component: path.resolve(`./src/templates/post.tsx`),
      // You can use the values in this context in
      // our page layout component
      context: { id: node.id },
    });
  });
};

export const onPostBuild: GatsbyNode['onPostBuild'] = ({ reporter }) => {
  reporter.info('Site Built!');
};

export const createPages: GatsbyNode['createPages'] = async ({
  actions,
  reporter,
  graphql,
}) => {
  const { createPage } = actions;

  await createTags(actions, reporter, graphql);
  await createPosts(actions, reporter, graphql);
};
