import type { Actions, GatsbyNode, Reporter } from 'gatsby';
const chunk = require(`lodash/chunk`);
const path = require(`path`);

const createPosts = async (actions: Actions, reporter: Reporter, graphql) => {
  const { createPage } = actions;

  const result = await graphql(`
    query PostsQuery {
      allMdx(
        filter: { frontmatter: { type: { eq: "post" } } }
        sort: { fields: frontmatter___date, order: DESC }
      ) {
        edges {
          node {
            id
            slug
            frontmatter {
              slug
            }
          }
        }
      }
    }
  `);

  if (result.errors) {
    reporter.panicOnBuild('🚨  ERROR: Loading "createPosts" query');
  }

  const posts = result.data.allMdx.edges

  posts.forEach(({ node }, index) => {
    createPage({
      // The slug generated by gatsby-plugin-mdx doesn't contain a slash at the beginning
      // You can prepend it with any prefix you want
      path: `/post/${node.frontmatter.slug}`,
      // This component will wrap our MDX content
      component: path.resolve(`./src/templates/post.tsx`),
      // You can use the values in this context in
      // our page layout component
      context: { id: node.id },
    })
  })
};

export const onPostBuild: GatsbyNode['onPostBuild'] = ({ reporter }) => {
  reporter.info('Site Built!');
};

export const createPages: GatsbyNode['createPages'] = async ({
  actions,
  reporter,
  graphql,
}) => {
  const { createPage } = actions;

  await createPosts(actions, reporter, graphql);
};
